
name: window_utils_macos
description: macOS implementation of the window_utils plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WindowUtilsPlugin
        fileName: window_utils_macos.dart

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0